[project]
name = "backend"
version = "0.1.0"
description = "RAG Evaluation Pipeline Project (Local Version)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.0",
    "uvicorn>=0.30.0",
    "sqlalchemy>=2.0.0",
    "python-dotenv>=1.2.2",
    "python-multipart>=0.0.22",
    "pymupdf>=1.27.2.2",
    "groq==0.31.0",
    "pydantic-settings>=2.13.1",
    "ragas>=0.4.3",
    "langchain-groq>=1.1.2",
    "langchain-huggingface>=0.0.3",
    "sentence-transformers>=3.0.0",
    "datasets>=4.8.4",
]

[tool.uv]
managed = true

[dependency-groups]
dev = []